### ISSUE TITLE
Add metadata

### ISSUE THREAD

**Issue by PrimusLV** [Muqsit/Sell#1]
``` yaml
249:1: 50
# Or
Glowing Obsidian: 50
```

**Comment by Muqsit** [comment]
oh but it would have to be in commas
`"Glowing Obsidian": 50`
...I am guessing.

**Comment by PrimusLV** [comment]
Perhaps :D

**Comment by ghost** [comment]
That's easy

**Comment by Muqsit** [comment]
@KairusDarkSeeker
if you can contribute, then please =D

**Comment by ghost** [comment]
@Muqsit lol okay

**Comment by Infernus101** [comment]
Add amount of item to be sold not lower than that

**Comment by Muqsit** [comment]
@Infernus101 There's no need of it. You only configure the price per 1 amount of X item in all quick sell plugins. The idea of adding count is pretty useless.

**Comment by Nickleog** [comment]
U sure nigga?

**Comment by Tolo0** [comment]
is they a permission node I can give to guest? seems abit pointless only ops having perm.

**Comment by Infernus101** [comment]
Check plugin.yml

**Comment by Infernus101** [comment]
sell.hand and sell.all

**Comment by Infernus101** [comment]
https://github.com/Muqsit/Sell/issues/14 - for more reference @Tolo0

**Comment by Infernus101** [comment]
@Tolo0

**Comment by Tolo0** [comment]
ok thanks 😊

**Comment by Infernus102** [comment]
why is this issue still open?

**Comment by ghost** [comment]
close it muq

**Comment by Infernus102** [comment]
harvey hans is right!

**Comment by Muqsit** [comment]
Check how its done in the sell.yml

**Comment by ghost** [comment]
@Infernus102 how tf did u know my name

**Comment by Infernus102** [comment]
Check your github profile noob -_-
